#!/bin/sh

#
# This script is heavly based on ntfs-3g mac osx package,
# thanks to Erik Larsson, and Paul Marks for their efforts.
#

function ShowDialog () {
    MESSAGE=$1
    osascript - "$1" <<-"EOF" > /dev/null &
      on run argv
        tell application "SystemUIServer" to display dialog item 1 of argv
      end run
EOF
}

while [[ "$1" = "-o" ]]; do
	shift 2
done

while ( [[ $# -ne 0 ]] ); do
if ( [[ $# -eq 1 ]] ) ; then
	MOUNTPOINT="$1"
elif ( [[ $# -eq 2 ]] ); then
	DEVICE_ARG="$1"
fi
shift
done

/Library/Filesystems/fusefs_hfs.fs/Contents/MacOS/fuse_wait "${MOUNTPOINT}" 5 /Library/Filesystems/fusefs_hfs.fs/Contents/MacOS/fusefs_hfs "${DEVICE_ARG}" "${MOUNTPOINT}"
